# Generated by Django 5.0.2 on 2024-05-02 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='titulo',
            new_name='title',
        ),
    ]
