# Generated by Django 5.0.2 on 2024-05-07 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_animal', models.CharField(max_length=100)),
                ('predador', models.CharField(max_length=100)),
                ('venenoso', models.CharField(max_length=100)),
                ('domestico', models.CharField(max_length=100)),
            ],
        ),
    ]
